In [ ]:
time started this at 45:50

In [4]:
train_file_path = r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_ingestion\2025-05-10-09-48-12\ingested_data\train\housing.csv"

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(train_file_path)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
0          2237.0       706.0         2.1736             72100.0   
1          2015.0       768.0         6.3373            279600.0   
2           667.0       300.0         2.8750             82700.0   
3           898.0       483.0         2.2264            112500.0   
4          1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
16507      2026.0      1001.0         5.0900            268500.0   
16508      4769.0      1418.0         2.8139             90400.0   
16509       458.0       172.0         3.1797            140400.0   
16510      1208.0       501.0         4.1964            258100.0   
16511       625.0       197.0         3.1319             62700.0   

      ocean_proximity  
0              INLAND  
1          NEAR OCEAN  
2              INLAND  
3          NEAR OCEAN  
4           <1H OCEAN  
...               ...  
16507       <1H OCEAN  
16508          INLAND  
16509       <1H OCEAN  
16510       <1H OCEAN  
16511          INLAND  

[16512 rows x 10 columns]

In [20]:
df.shape

(16512, 10)

In [21]:
df['median_house_value']

0         72100.0
1        279600.0
2         82700.0
3        112500.0
4        238300.0
           ...   
16507    268500.0
16508     90400.0
16509    140400.0
16510    258100.0
16511     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [7]:
x,y = df.drop(columns=['median_house_value'],axis=1),df[['median_house_value']]

In [23]:
x.shape

(16512, 9)

In [25]:
y.shape

(16512, 1)

In [27]:
x.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND  
1      2015.0       768.0         6.3373      NEAR OCEAN  
2       667.0       300.0         2.8750          INLAND

In [35]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [36]:
x.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [8]:
from sklearn.impute import SimpleImputer # SimpleImputer will be applicable for Numerical columns so if there
                                         # any null value it can populate it,

In [9]:
numerical_columns = x.drop(columns=['ocean_proximity'])
numerical_columns.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   

   population  households  median_income  
0      2237.0       706.0         2.1736  
1      2015.0       768.0         6.3373

In [10]:
numerical_columns.shape

(16512, 8)

In [11]:
simple_imputer = SimpleImputer(strategy="median")

In [12]:
simple_imputer.fit_transform(numerical_columns)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [13]:
df = simple_imputer.transform(numerical_columns)

In [14]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [15]:
simple_imputer.statistics_  # these are the median values of every column if any null values found
                            # through which we will replace those respective columns

                            # example we have null/missing values in "total_bedrooms" when we call
                            # simple_imputer.transform or simple_imputer.fit_transform it will replce
                            # the null/missing values with the mean/median/most_frequent/constant
                            # of those specific columns, and give transformed data,


array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [66]:
# conformation Median or not
numerical_columns['longitude'].median()

np.float64(-118.51)

In [16]:
for i in numerical_columns.columns:
    print(f"median of {i} = ",numerical_columns[i].median())

median of longitude =  -118.51
median of latitude =  34.26
median of housing_median_age =  29.0
median of total_rooms =  2119.0
median of total_bedrooms =  433.0
median of population =  1164.0
median of households =  408.0
median of median_income =  3.54155


In [68]:
numerical_columns.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
dtype: int64

In [69]:
x.ocean_proximity

0            INLAND
1        NEAR OCEAN
2            INLAND
3        NEAR OCEAN
4         <1H OCEAN
            ...    
16507     <1H OCEAN
16508        INLAND
16509     <1H OCEAN
16510     <1H OCEAN
16511        INLAND
Name: ocean_proximity, Length: 16512, dtype: object

In [71]:
x.ocean_proximity.isna().sum()

np.int64(0)

In [ ]:
x.columns

In [17]:
categorical_columns = x.ocean_proximity
categorical_columns

0            INLAND
1        NEAR OCEAN
2            INLAND
3        NEAR OCEAN
4         <1H OCEAN
            ...    
16507     <1H OCEAN
16508        INLAND
16509     <1H OCEAN
16510     <1H OCEAN
16511        INLAND
Name: ocean_proximity, Length: 16512, dtype: object

In [18]:
simple_imputer_cat = SimpleImputer(strategy="most_frequent")

In [ ]:
simple_imputer_cat.transform(categorical_columns)

In [75]:
#custome Transformer
class FeatureGenerator():
    def __init__(self,stratagy="median"):
        self.stratagy=stratagy

    def fit(self,X):
        self._features = X.columns
        self._statistics =[]
        for column in X.columns:
            self._statistics.append(X[column].median())

        return self
    
    def transform(self,X:pd.DataFrame):
        for index,column in X.columns:
            X[column].fillna(self._statistics[index])

    def fit_transform(self,X:pd.DataFrame):
        self.fit(X)
        return self.transform(X)





In [36]:
response = FeatureGenerator().fit(numerical_columns)

In [38]:
response.stratagy

'median'

In [39]:
response._features

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [40]:
response._statistics

[np.float64(-118.51),
 np.float64(34.26),
 np.float64(29.0),
 np.float64(2119.0),
 np.float64(433.0),
 np.float64(1164.0),
 np.float64(408.0),
 np.float64(3.54155)]

In [2]:
from sklearn.base import  BaseEstimator, TransformerMixin

In [76]:
class FeatureGenerator(BaseEstimator,TransformerMixin):
                                                         # when you inherit TransformerMixin you dont have to write 
                                                         # fit_transform it only
    def __init__(self,stratagy="median"):
        self.stratagy=stratagy

    def fit(self,X):
        self._features = X.columns
        self._statistics =[]
        for column in X.columns:
            self._statistics.append(X[column].median())

        return self._statistics
    
    def transform(self,X:pd.DataFrame):
        for index,column in X.columns:
            X[column].fillna(self._statistics[index])




In [45]:
from housing.exception import HousingException
import os,sys

In [46]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [53]:
columns = x.columns
columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [55]:
COLUMN_TOTAL_ROOMS =3
columns.index(COLUMN_TOTAL_ROOMS)

AttributeError: 'Index' object has no attribute 'index'

In [58]:
x.index

RangeIndex(start=0, stop=16512, step=1)

In [69]:
x['total_bedrooms']/x['total_rooms']

0        0.205784
1        0.160714
2        0.191595
3        0.276505
4        0.182692
           ...   
16507    0.184696
16508    0.179977
16509    0.234795
16510    0.183835
16511    0.205746
Length: 16512, dtype: float64

In [106]:
import numpy as np

In [83]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"
DATASET_SCHEMA_COLUMNS_KEY=  "columns"

NUMERICAL_COLUMN_KEY="numerical_columns"
CATEGORICAL_COLUMN_KEY = "categorical_columns"

TARGET_COLUMN_KEY="target_column"

                  #  ('feature_genrator',FeatureGenerator())
class FeatureGenerator(BaseEstimator, TransformerMixin):
                                                        # ['longitude', 'latitude', 'housing_median_age', 'total_rooms','total_bedrooms', 'population', 'households', 'median_income','ocean_proximity']
    def __init__(self, 
                 add_bedrooms_per_room=True,
                 total_rooms_ix=3,
                 total_bedrooms_ix=4,
                 population_ix=5,
                 households_ix=6,
                 columns=None
                 ):
        """
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of  households columns
        total_bedrooms_ix: int index number of bedrooms columns
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.total_bedrooms_ix = total_bedrooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            
        except Exception as e:
            raise  HousingException(os,sys) from e

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / \
                                 X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / \
                                       X[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = X[:, self.total_bedrooms_ix] / \
                                    X[:, self.total_rooms_ix]
                generated_feature = np.c_[
                    X, room_per_household, population_per_household, bedrooms_per_room]
            else:
                generated_feature = np.c_[
                    X, room_per_household, population_per_household]

            return generated_feature
        except Exception as e:
            raise  HousingException(os,sys) from e

In [122]:
arr1=np.arange(10)
arr2=np.arange(10)

In [ ]:
np.c_[arr1,arr2] # cancatinate the columns in this way 

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [78]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# we can create sapearate pipeline for the "numerical column" and
# "catogorical column"  at final stage we combine these numerical and
# categorical transformers columns so we use ColumnTransformer

In [79]:
from sklearn.preprocessing import StandardScaler

In [84]:
# Numerical Pipeline

num_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('feature_genrator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [85]:
from sklearn.preprocessing import OneHotEncoder

In [86]:
# Categorical pipeline

cat_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('OneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [98]:
num_columns_names = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
                     'total_bedrooms', 'population', 'households', 'median_income']
cat_column_name = ['ocean_proximity']

In [99]:
preprocessing_obj = ColumnTransformer([
    ('num_pipeline',num_pipeline,num_columns_names),
    ('cat_pipeline',cat_pipeline,cat_column_name)
])

In [100]:
preprocessing_obj

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('feature_genrator',
                                                  FeatureGenerator()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder()),
                                                 ('scaling',
                                                  StandardScaler(with_mean=False))]),
                                 ['ocean_proximity'])])

In [104]:
df = pd.read_csv(train_file_path)

In [107]:
preprocessing_obj.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [108]:
test_file_path =r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_ingestion\2025-05-10-09-48-12\ingested_data\test\housing.csv"

In [110]:
test_df = pd.read_csv(test_file_path)
test_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -118.39     34.12                29.0       6447.0          1012.0   
1       -120.42     34.89                24.0       2020.0           307.0   
2       -118.45     34.25                36.0       1453.0           270.0   
3       -118.10     33.91                35.0       1653.0           325.0   
4       -117.07     32.77                38.0       3779.0           614.0   
...         ...       ...                 ...          ...             ...   
4123    -117.29     33.72                19.0       2248.0           427.0   
4124    -118.24     33.99                33.0        885.0           294.0   
4125    -119.72     34.44                43.0       1781.0           342.0   
4126    -117.91     33.63                30.0       2071.0           412.0   
4127    -118.56     34.19                36.0       2600.0           441.0   

      population  households  median_income  median_house_value  \
0         2184.0       960.0         8.2816            500001.0   
1          855.0       283.0         5.0099            162500.0   
2          808.0       275.0         4.3839            204600.0   
3         1072.0       301.0         3.2708            159700.0   
4         1495.0       614.0         4.3529            184000.0   
...          ...         ...            ...                 ...   
4123      1207.0       368.0         2.8170            110000.0   
4124      1270.0       282.0         2.1615            118800.0   
4125       663.0       358.0         4.7000            293800.0   
4126      1081.0       412.0         4.9125            335700.0   
4127      1246.0       426.0         4.1111            215600.0   

     ocean_proximity  
0          <1H OCEAN  
1          <1H OCEAN  
2          <1H OCEAN  
3          <1H OCEAN  
4         NEAR OCEAN  
...              ...  
4123       <1H OCEAN  
4124       <1H OCEAN  
4125       <1H OCEAN  
4126       <1H OCEAN  
4127       <1H OCEAN  

[4128 rows x 10 columns]

In [111]:
preprocessing_obj.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])

In [113]:
import dill

In [114]:
dill.dump

<function dill._dill.dump(obj, file, protocol=None, byref=None, fmode=None, recurse=None, **kwds)>

In [115]:
with open("preprocessing.pkl","wb") as pre_file:
    dill.dump(obj=preprocessing_obj,file=pre_file)

In [116]:
with open("preprocessing_2.pkl","wb") as pre_file:
    dill.dump(preprocessing_obj,pre_file)

In [117]:
with open("preprocessing_2.pkl","rb") as file_obj:
    preprocessing_loaded_obj = dill.load(file_obj)

In [118]:
preprocessing_loaded_obj.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])

In [119]:
preprocessing_loaded_obj.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'], dtype=object)

In [120]:
preprocessing_loaded_obj.transformers

[('num_pipeline',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                  ('feature_genrator', FeatureGenerator()),
                  ('scaling', StandardScaler())]),
  ['longitude',
   'latitude',
   'housing_median_age',
   'total_rooms',
   'total_bedrooms',
   'population',
   'households',
   'median_income']),
 ('cat_pipeline',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                  ('OneHotEncoder', OneHotEncoder()),
                  ('scaling', StandardScaler(with_mean=False))]),
  ['ocean_proximity'])]

In [121]:
preprocessing_loaded_obj

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('feature_genrator',
                                                  FeatureGenerator()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder()),
                                                 ('scaling',
                                                  StandardScaler(with_mean=False))]),
                                 ['ocean_proximity'])])