In [1]:
from housing.entity import housing_predictor

In [2]:
train_file_path =r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_ingestion\2025-05-21-22-56-40\ingested_data\train\housing.csv"

In [3]:
import pandas as pd
df2 = pd.read_csv(train_file_path)
df2.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [4]:
df2[(df2[df2['ocean_proximity']=='<1H OCEAN']) and (df2[df2['longitude']==-118.39])]

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [5]:
housing_data = housing_predictor.HousingData(-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,'INLAND')
housing_data

In [6]:
housing_data.get_housing_data_as_dict()

{'longitude': [-121.46],
 'latitude': [38.52],
 'housing_median_age': [29.0],
 'total_rooms': [3873.0],
 'total_bedrooms': [797.0],
 'population': [2237.0],
 'households': [706.0],
 'median_income': [2.1736],
 'ocean_proximity': ['INLAND']}

In [24]:
df = housing_data.get_housing_input_data_frame()
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND

In [8]:
print(housing_data.median_house_value)

None


In [9]:
housing_data.latitude

38.52

In [10]:
from housing.entity.housing_predictor import HousingPredictor

In [17]:
import os
os.chdir("d:\\ML_Projects\\MLOps_California_House_Price_Prediction")
SAVED_MODELS_DIR_NAME = "saved_models"
ROOT_DIR = os.getcwd()
MODEL_DIR = os.path.join(ROOT_DIR, SAVED_MODELS_DIR_NAME)
MODEL_DIR

'd:\\ML_Projects\\MLOps_California_House_Price_Prediction\\saved_models'

In [18]:
housing_predictor = HousingPredictor(model_dir=MODEL_DIR)

In [25]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND

In [29]:
housing_predictor.predict(X=df)[0]

np.float64(85657.90192014378)

In [23]:
df2.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND

In [ ]:
import pandas as pd

# Sample data
df = pd.DataFrame({
    'gender': ['male', 'female', 'other', 'unknown', 'mle']
})

# Define valid domain
valid_values = {'male', 'female', 'other'}

# Check for invalid values
invalid_rows = df[~df['gender'].isin(valid_values)]

print("Invalid values found: ")

print(invalid_rows)

Invalid values found:
    gender
3  unknown
4      mle


In [31]:
data_ingestion_test_file_path = r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_ingestion\2025-05-22-12-13-20\ingested_data\test\housing.csv"

df = pd.read_csv(data_ingestion_test_file_path)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -118.39     34.12                29.0       6447.0          1012.0   
1       -120.42     34.89                24.0       2020.0           307.0   
2       -118.45     34.25                36.0       1453.0           270.0   
3       -118.10     33.91                35.0       1653.0           325.0   
4       -117.07     32.77                38.0       3779.0           614.0   
...         ...       ...                 ...          ...             ...   
4123    -117.29     33.72                19.0       2248.0           427.0   
4124    -118.24     33.99                33.0        885.0           294.0   
4125    -119.72     34.44                43.0       1781.0           342.0   
4126    -117.91     33.63                30.0       2071.0           412.0   
4127    -118.56     34.19                36.0       2600.0           441.0   

      population  households  median_income  median_house_value  \
0         2184.0       960.0         8.2816            500001.0   
1          855.0       283.0         5.0099            162500.0   
2          808.0       275.0         4.3839            204600.0   
3         1072.0       301.0         3.2708            159700.0   
4         1495.0       614.0         4.3529            184000.0   
...          ...         ...            ...                 ...   
4123      1207.0       368.0         2.8170            110000.0   
4124      1270.0       282.0         2.1615            118800.0   
4125       663.0       358.0         4.7000            293800.0   
4126      1081.0       412.0         4.9125            335700.0   
4127      1246.0       426.0         4.1111            215600.0   

     ocean_proximity  
0          <1H OCEAN  
1          <1H OCEAN  
2          <1H OCEAN  
3          <1H OCEAN  
4         NEAR OCEAN  
...              ...  
4123       <1H OCEAN  
4124       <1H OCEAN  
4125       <1H OCEAN  
4126       <1H OCEAN  
4127       <1H OCEAN  

[4128 rows x 10 columns]

In [34]:
import os
os.chdir("d:\\ML_Projects\\MLOps_California_House_Price_Prediction")
SAVED_MODELS_DIR_NAME = "saved_models"
ROOT_DIR = os.getcwd()
MODEL_DIR = os.path.join(ROOT_DIR, SAVED_MODELS_DIR_NAME)
MODEL_DIR
from housing.entity.housing_predictor import HousingPredictor

In [35]:
housing_batch_predict = HousingPredictor(model_dir=MODEL_DIR)

In [36]:
df.shape

(4128, 10)

In [37]:
df['median_house_value']

0       500001.0
1       162500.0
2       204600.0
3       159700.0
4       184000.0
          ...   
4123    110000.0
4124    118800.0
4125    293800.0
4126    335700.0
4127    215600.0
Name: median_house_value, Length: 4128, dtype: float64

In [39]:
pred= housing_batch_predict.predict(X=df)

In [41]:
pred.shape

(4128,)

In [42]:
df.shape

(4128, 10)

In [43]:
df['median_house_value']

0       500001.0
1       162500.0
2       204600.0
3       159700.0
4       184000.0
          ...   
4123    110000.0
4124    118800.0
4125    293800.0
4126    335700.0
4127    215600.0
Name: median_house_value, Length: 4128, dtype: float64

In [46]:
df2 = df.drop(columns=['median_house_value'])
df2.shape

(4128, 9)

In [49]:
pred_df2 = housing_predictor.predict(X=df2)

In [50]:
pred_df2.shape

(4128,)

In [58]:
single_record = pd.DataFrame(df[:1].to_dict())

In [59]:
housing_predictor.predict(X=single_record)

array([424327.43173199])

In [60]:
single_record

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -118.39     34.12                29.0       6447.0          1012.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2184.0       960.0         8.2816            500001.0       <1H OCEAN

In [61]:
df[:1]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -118.39     34.12                29.0       6447.0          1012.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2184.0       960.0         8.2816            500001.0       <1H OCEAN

In [62]:
housing_predictor.predict(X=df[:1])

array([424327.43173199])

In [63]:
housing_predictor.predict(X=df[:2])


array([424327.43173199, 290941.55056488])

In [2]:
import os
os.chdir("d:\\ML_Projects\\MLOps_California_House_Price_Prediction")
SAVED_MODELS_DIR_NAME = "saved_models"
ROOT_DIR = os.getcwd()
MODEL_DIR = os.path.join(ROOT_DIR, SAVED_MODELS_DIR_NAME)
model_dir = MODEL_DIR

In [66]:
os.listdir(model_dir)

['20250519100612',
 '20250519114615',
 '20250519154013',
 '20250519161845',
 '20250521100626',
 '20250521224614',
 '20250521230036',
 '20250521230850',
 '20250522121729']

In [68]:
map(int, os.listdir(model_dir))

In [71]:
folder_name = list(map(int, os.listdir(model_dir)))
folder_name

[20250519100612,
 20250519114615,
 20250519154013,
 20250519161845,
 20250521100626,
 20250521224614,
 20250521230036,
 20250521230850,
 20250522121729]

In [72]:
max(folder_name)

20250522121729

In [73]:
model_dir

'd:\\ML_Projects\\MLOps_California_House_Price_Prediction\\saved_models'

In [74]:
latest_model_dir = os.path.join(model_dir, f"{max(folder_name)}")
latest_model_dir

'd:\\ML_Projects\\MLOps_California_House_Price_Prediction\\saved_models\\20250522121729'

In [ ]:
file_name = os.listdir(latest_model_dir)[0]
file_name

'model.pkl'

In [76]:
latest_model_path = os.path.join(latest_model_dir, file_name)
latest_model_path

'd:\\ML_Projects\\MLOps_California_House_Price_Prediction\\saved_models\\20250522121729\\model.pkl'

In [6]:
import os,sys
from housing.logger import logging
from housing.exception import HousingException
def get_latest_model_path(model_dir:str):
        """ 
        This function will help you to get latest model file path from
        "Saved_models" Directory so that we can loaad the latest model
        and do the prdiction 
        """
        try:
            folder_name = list(map(int, os.listdir(model_dir)))
            latest_model_dir = os.path.join(model_dir, f"{max(folder_name)}")
            file_name = os.listdir(latest_model_dir)[0]
            latest_model_path = os.path.join(latest_model_dir, file_name)
            return latest_model_path
        except Exception as e:
            raise HousingException(e, sys) from e

In [7]:
get_latest_model_path(model_dir=MODEL_DIR)

'd:\\ML_Projects\\MLOps_California_House_Price_Prediction\\saved_models\\20250522121729\\model.pkl'