In [4]:
from housing.entity.model_factory import ModelFactory,get_sample_model_config_yaml_file

In [5]:
get_sample_model_config_yaml_file(export_dir="config")

'config\\model.yaml'

In [15]:
model_config_file =r"D:\ML_Projects\MLOps_California_House_Price_Prediction\notebook\config\model.yaml"

In [ ]:
model_config_file =r"D:\ML_Projects\MLOps_California_House_Price_Prediction\notebook\config\model.yaml"

model_factory = ModelFactory(model_config_path=model_config_file)

In [12]:
model_list = model_factory.get_initialized_model_list()

{'fit_intercept': True}
{'n_estimators': 40, 'min_samples_leaf': 2}


In [13]:
import os,sys
from housing.exception import HousingException
import yaml

def read_params(config_path: str) -> dict:
        """
        read the yaml file and returns 
        the yamle file as dictionary
        """
        try:
            with open(config_path) as yaml_file:
                config:dict = yaml.safe_load(yaml_file)
            return config
        except Exception as e:
            raise HousingException(e, sys) from e

In [19]:
GRID_SEARCH_KEY = 'grid_search'
MODULE_KEY = 'module'
CLASS_KEY = 'class'
PARAM_KEY = 'params'
MODEL_SELECTION_KEY = 'model_selection'
SEARCH_PARAM_GRID_KEY = "search_param_grid"
config = read_params(config_path=model_config_file)
config

{'grid_search': {'class': 'GridSearchCV',
  'module': 'sklearn.model_selection',
  'params': {'cv': 4, 'verbose': 2}},
 'model_selection': {'module_0': {'class': 'LinearRegression',
   'module': 'sklearn.linear_model',
   'params': {'fit_intercept': True},
   'search_param_grid': {'fit_intercept': [True, False]}},
  'module_1': {'class': 'RandomForestRegressor',
   'module': 'sklearn.ensemble',
   'params': {'n_estimators': 40, 'min_samples_leaf': 2},
   'search_param_grid': {'min_samples_leaf': [2, 4, 6],
    'n_estimators': [50, 100, 80]}}}}

In [29]:
models_initialization_config = config[MODEL_SELECTION_KEY]
models_initialization_config

{'module_0': {'class': 'LinearRegression',
  'module': 'sklearn.linear_model',
  'params': {'fit_intercept': True},
  'search_param_grid': {'fit_intercept': [True, False]}},
 'module_1': {'class': 'RandomForestRegressor',
  'module': 'sklearn.ensemble',
  'params': {'n_estimators': 40, 'min_samples_leaf': 2},
  'search_param_grid': {'min_samples_leaf': [2, 4, 6],
   'n_estimators': [50, 100, 80]}}}

In [31]:
models_initialization_config.keys()

dict_keys(['module_0', 'module_1'])

In [23]:
grid_search_cv_module: str = config[GRID_SEARCH_KEY][MODULE_KEY]
grid_search_class_name: str = config[GRID_SEARCH_KEY][CLASS_KEY]

In [26]:
print(grid_search_cv_module)
print(grid_search_class_name)

sklearn.model_selection
GridSearchCV


In [32]:
model_serial_number = ['module_0', 'module_1']

In [35]:
models_initialization_config

{'module_0': {'class': 'LinearRegression',
  'module': 'sklearn.linear_model',
  'params': {'fit_intercept': True},
  'search_param_grid': {'fit_intercept': [True, False]}},
 'module_1': {'class': 'RandomForestRegressor',
  'module': 'sklearn.ensemble',
  'params': {'n_estimators': 40, 'min_samples_leaf': 2},
  'search_param_grid': {'min_samples_leaf': [2, 4, 6],
   'n_estimators': [50, 100, 80]}}}

In [34]:
model_initialization_config = models_initialization_config[model_serial_number[0]]
model_initialization_config

{'class': 'LinearRegression',
 'module': 'sklearn.linear_model',
 'params': {'fit_intercept': True},
 'search_param_grid': {'fit_intercept': [True, False]}}

In [36]:
model_initialization_config = models_initialization_config['module_0']
model_initialization_config

{'class': 'LinearRegression',
 'module': 'sklearn.linear_model',
 'params': {'fit_intercept': True},
 'search_param_grid': {'fit_intercept': [True, False]}}

In [41]:
module_name=model_initialization_config[MODULE_KEY]
class_name=model_initialization_config[CLASS_KEY]
print(module_name)

print(class_name)

sklearn.linear_model
LinearRegression


In [44]:
models_initialization_config

{'module_0': {'class': 'LinearRegression',
  'module': 'sklearn.linear_model',
  'params': {'fit_intercept': True},
  'search_param_grid': {'fit_intercept': [True, False]}},
 'module_1': {'class': 'RandomForestRegressor',
  'module': 'sklearn.ensemble',
  'params': {'n_estimators': 40, 'min_samples_leaf': 2},
  'search_param_grid': {'min_samples_leaf': [2, 4, 6],
   'n_estimators': [50, 100, 80]}}}

In [51]:
if PARAM_KEY in models_initialization_config:
    model_obj_property_data = dict(model_initialization_config[PARAM_KEY])

In [48]:
model_initialization_config[PARAM_KEY]

{'fit_intercept': True}

In [54]:
models_initialization_config['module_1'][PARAM_KEY]

{'n_estimators': 40, 'min_samples_leaf': 2}

In [56]:
from sklearn.linear_model import LinearRegression

In [58]:
property_data = model_initialization_config[PARAM_KEY]
property_data

{'fit_intercept': True}

In [63]:
class_name =grid_search_class_name
class_name

'GridSearchCV'

In [65]:
module_name= grid_search_cv_module
module_name

'sklearn.model_selection'

In [67]:
import importlib

module = importlib.import_module(module_name)

class_ref = getattr(module, class_name)
class_ref

sklearn.model_selection._search.GridSearchCV

In [69]:
module_name = 'sklearn.linear_model'
class_name = 'LinearRegression'
module = importlib.import_module(module_name)

class_ref = getattr(module, class_name)
class_ref

sklearn.linear_model._base.LinearRegression

In [70]:
property_data

{'fit_intercept': True}

In [72]:
model_obj_ref = class_ref
model_obj_ref

sklearn.linear_model._base.LinearRegression

In [74]:
model = model_obj_ref()
model

LinearRegression()

In [76]:
instance_ref = model
instance_ref

LinearRegression()

In [77]:
property_data

{'fit_intercept': True}

In [78]:
from housing.logger import logging
def update_property_of_class(instance_ref:object, property_data: dict):
        """ 
        initialize parameters of Modules 
        """
        try:
            if not isinstance(property_data, dict):
                raise Exception("property_data parameter required to dictionary")
            print(property_data)
            for key, value in property_data.items():
                logging.info(f"Executing:$ {str(instance_ref)}.{key}={value}")
                setattr(instance_ref, key, value) # setattr(LinearRegression, 'fit_intercept', True)
                # setattr is responsible for if you want to set dynamically the parameters of any ML model class
                # you can use "setattr" function {check the notebook inside importlib.ipynb there explained 
                # "setattr" fun similar
            return instance_ref
        except Exception as e:
            raise HousingException(e, sys) from e

In [ ]:
update_property_of_class(instance_ref=instance_ref,property_data=property_data)

{'fit_intercept': True}


LinearRegression()

In [80]:
model_initialization_config

{'class': 'LinearRegression',
 'module': 'sklearn.linear_model',
 'params': {'fit_intercept': True},
 'search_param_grid': {'fit_intercept': [True, False]}}

In [83]:
param_grid_search = model_initialization_config[SEARCH_PARAM_GRID_KEY]
model_name = f"{model_initialization_config[MODULE_KEY]}.{model_initialization_config[CLASS_KEY]}"
print(param_grid_search)
print(model_name)

{'fit_intercept': [True, False]}
sklearn.linear_model.LinearRegression


In [84]:
from housing.entity.model_factory import InitializedModelDetail
model_initialization_config = InitializedModelDetail(model_serial_number=model_serial_number,
                                                                     model=model,
                                                                     param_grid_search=param_grid_search,
                                                                     model_name=model_name
                                                                     )

In [85]:
model_initialization_config

InitializedModelDetail(model_serial_number=['module_0', 'module_1'], model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression')

In [86]:
model_config_file =r"D:\ML_Projects\MLOps_California_House_Price_Prediction\notebook\config\model.yaml"

model_factory = ModelFactory(model_config_path=model_config_file)

In [88]:
model_list = model_factory.get_initialized_model_list()

{'fit_intercept': True}
{'n_estimators': 40, 'min_samples_leaf': 2}


In [89]:
model_list

[InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression'),
 InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), param_grid_search={'min_samples_leaf': [2, 4, 6], 'n_estimators': [50, 100, 80]}, model_name='sklearn.ensemble.RandomForestRegressor')]

In [90]:
len(model_list)

2

In [91]:
model_list[0]

InitializedModelDetail(model_serial_number='module_0', model=LinearRegression(), param_grid_search={'fit_intercept': [True, False]}, model_name='sklearn.linear_model.LinearRegression')

In [92]:
model_list[1]

InitializedModelDetail(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), param_grid_search={'min_samples_leaf': [2, 4, 6], 'n_estimators': [50, 100, 80]}, model_name='sklearn.ensemble.RandomForestRegressor')

In [94]:
from housing.util.util import load_numpy_array_data

In [ ]:
data_file_path = r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_transformation\2025-05-14-15-27-33\transformed_data\train\housing.npz"

data = load_numpy_array_data(file_path=data_file_path)
data

array([[-9.41350459e-01,  1.34743822e+00,  2.75635714e-02, ...,
         0.00000000e+00,  0.00000000e+00,  7.21000000e+04],
       [ 1.17178212e+00, -1.19243966e+00, -1.72201763e+00, ...,
         0.00000000e+00,  2.98691050e+00,  2.79600000e+05],
       [ 2.67581180e-01, -1.25971599e-01,  1.22045984e+00, ...,
         0.00000000e+00,  0.00000000e+00,  8.27000000e+04],
       ...,
       [-1.57079420e+00,  1.31001828e+00,  1.53856552e+00, ...,
         0.00000000e+00,  0.00000000e+00,  1.40400000e+05],
       [-1.56080303e+00,  1.24921090e+00, -1.16533270e+00, ...,
         0.00000000e+00,  0.00000000e+00,  2.58100000e+05],
       [-1.28105026e+00,  2.02567448e+00, -1.31489265e-01, ...,
         0.00000000e+00,  0.00000000e+00,  6.27000000e+04]])

In [101]:
x,y = data[:,:-1],data[:,-1]

In [ ]:
x # input features of the training dataset 

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
y # terget feature of the training daytaset

array([ 72100., 279600.,  82700., ..., 140400., 258100.,  62700.])

In [ ]:
data_file_path = r"D:\ML_Projects\MLOps_California_House_Price_Prediction\housing\artifact\data_transformation\2025-05-14-15-27-33\transformed_data\train\housing.npz"

data = load_numpy_array_data(file_path=data_file_path)
data

In [114]:
best_model = model_factory.get_best_model(X=x,y=y,base_accuracy=0.9)

{'fit_intercept': True}
{'n_estimators': 40, 'min_samples_leaf': 2}
{'cv': 4, 'verbose': 2}
Fitting 4 folds for each of 2 candidates, totalling 8 fits
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END .................................fit_intercept=True; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.1s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
[CV] END ................................fit_intercept=False; total time=   0.0s
{'cv': 4, 'verbose': 2}
Fitting 4 folds for each of 9 candidates, totalling 36 fits
[CV] END ................min_samples_leaf=2, n_estimators=50; total time=  15.0s
[CV] END ................min_samples

HousingException: 
        Error occured in script:
        [ d:\ml_projects\mlops_california_house_price_prediction\housing\entity\model_factory.py ] at 
        try block line number: [416] and exception block line number: [419] 
        error message: [
        Error occured in script:
        [ d:\ml_projects\mlops_california_house_price_prediction\housing\entity\model_factory.py ] at 
        try block line number: [388] and exception block line number: [392] 
        error message: [None of Model has base accuracy: 0.9]
        
        ]
        
        

In [108]:
best_model

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=np.float64(0.805956279380061))

In [109]:
best_model.best_model

RandomForestRegressor(min_samples_leaf=2)

In [110]:
best_model.best_score

np.float64(0.805956279380061)

In [111]:
model_factory.grid_searched_best_model_list

[GridSearchedBestModel(model_serial_number='module_0', model=LinearRegression(), best_model=LinearRegression(fit_intercept=False), best_parameters={'fit_intercept': False}, best_score=np.float64(0.6393153733826)),
 GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=np.float64(0.805956279380061))]

In [112]:
model_factory.grid_searched_best_model_list[0]

GridSearchedBestModel(model_serial_number='module_0', model=LinearRegression(), best_model=LinearRegression(fit_intercept=False), best_parameters={'fit_intercept': False}, best_score=np.float64(0.6393153733826))

In [113]:
model_factory.grid_searched_best_model_list[1]

GridSearchedBestModel(model_serial_number='module_1', model=RandomForestRegressor(min_samples_leaf=2, n_estimators=40), best_model=RandomForestRegressor(min_samples_leaf=2), best_parameters={'min_samples_leaf': 2, 'n_estimators': 100}, best_score=np.float64(0.805956279380061))